os: osx
osx_image: xcode9.1
before_install:
  - brew update  # node already installed
  - npm install -g 'cordova@6.5.0'
  - npm install -g 'grunt-cli@1.2.0' && npm install
  - bower install
  - cordova requirements
script:
    - cordova build
