os: osx
osx_image: xcode9.1
before_install:
  - brew update  # node already installed
  - npm install -g 'bower@1.7.9'
  - npm install -g 'cordova@6.5.0'
  - npm install -g 'grunt-cli@1.2.0' && npm install
  - bower install
    # copied from the Troubleshooting section
  - rm -rf platforms/android
  - cordova platform add android@6.1.2
  - git checkout -- platforms
  - cordova requirements
script:
    - cordova build
